"""Add deleted flag to materials

Revision ID: 023d07fbeaf2
Revises: 9a69c04ab912
Create Date: 2019-12-15 00:54:19.931299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023d07fbeaf2'
down_revision = '9a69c04ab912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course_Material', sa.Column('deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course_Material', 'deleted')
    # ### end Alembic commands ###
