"""empty message

Revision ID: 11550468b927
Revises: 0663c0c01436
Create Date: 2019-11-30 02:40:42.126491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11550468b927'
down_revision = '0663c0c01436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Social_Pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vk', sa.String(length=100), nullable=True),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('linked_in', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('UserSocial_Pages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSocial_Pages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UserSocial_Pages_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vk', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('linked_in', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='UserSocial_Pages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='UserSocial_Pages_pkey'),
    sa.UniqueConstraint('user_id', name='UserSocial_Pages_user_id_key')
    )
    op.drop_table('User_Social_Pages')
    # ### end Alembic commands ###
