"""empty message

Revision ID: 1bef3c3fc7a5
Revises: 11550468b927
Create Date: 2019-11-30 19:49:08.083542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef3c3fc7a5'
down_revision = '11550468b927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Info', sa.Column('detailed_description', sa.String(length=255), nullable=True))
    op.drop_column('User_Info', 'deltailed_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Info', sa.Column('deltailed_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('User_Info', 'detailed_description')
    # ### end Alembic commands ###
