"""empty message

Revision ID: 47009e0198b5
Revises: 
Create Date: 2019-12-15 21:04:16.713009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47009e0198b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint('Course_Responsible_Person_person_id_fkey', 'Course_Responsible_Person', type_='foreignkey')
    op.create_foreign_key(None, 'Course_Responsible_Person', 'students', ['person_id'], ['id'])
    op.create_foreign_key(None, 'EducationalСourse', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EducationalСourse', type_='foreignkey')
    op.drop_constraint(None, 'Course_Responsible_Person', type_='foreignkey')
    op.create_foreign_key('Course_Responsible_Person_person_id_fkey', 'Course_Responsible_Person', 'students', ['person_id'], ['user_id'])
    op.drop_table('teachers')
    # ### end Alembic commands ###
