"""empty message

Revision ID: 57184a3ac416
Revises: 1bef3c3fc7a5
Create Date: 2019-12-08 16:52:51.681174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57184a3ac416'
down_revision = '1bef3c3fc7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['EducationalСourse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course_Material')
    # ### end Alembic commands ###
