"""Add Course Responsible Person Table

Revision ID: 807622c61947
Revises: bd81e47bd709
Create Date: 2019-12-09 23:19:39.009853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807622c61947'
down_revision = 'bd81e47bd709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Responsible_Person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['EducationalСourse.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course_Responsible_Person')
    # ### end Alembic commands ###
