"""empty message

Revision ID: 9cfeb8d9d1ec
Revises: 57184a3ac416
Create Date: 2019-12-08 17:27:52.036694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfeb8d9d1ec'
down_revision = '57184a3ac416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course_Material', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('Course_Material', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course_Material', 'updated_on')
    op.drop_column('Course_Material', 'created_on')
    # ### end Alembic commands ###
