"""Add Hometasks

Revision ID: a17e80e452d1
Revises: 47009e0198b5
Create Date: 2020-01-10 00:26:53.059831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17e80e452d1'
down_revision = '47009e0198b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_hometask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('start_dttm', sa.DateTime(), nullable=False),
    sa.Column('end_dttm', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['EducationalСourse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_hometask')
    # ### end Alembic commands ###
