"""Add deleted flag to hometasks

Revision ID: b9acba47fd53
Revises: a17e80e452d1
Create Date: 2020-01-10 15:34:26.250684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9acba47fd53'
down_revision = 'a17e80e452d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_hometask', sa.Column('deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_hometask', 'deleted')
    # ### end Alembic commands ###
