"""empty message

Revision ID: bd81e47bd709
Revises: 9cfeb8d9d1ec
Create Date: 2019-12-08 21:07:27.897628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd81e47bd709'
down_revision = '9cfeb8d9d1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Course_Material', 'content',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('Course_Material', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Course_Material', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Course_Material', 'content',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    # ### end Alembic commands ###
