"""empty message

Revision ID: d22409a11ef7
Revises: bf8f2e143d68
Create Date: 2019-11-30 02:28:08.971468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22409a11ef7'
down_revision = 'bf8f2e143d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_info', ['user_id'])
    op.create_unique_constraint(None, 'user_social_pages', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_social_pages', type_='unique')
    op.drop_constraint(None, 'user_info', type_='unique')
    # ### end Alembic commands ###
